# Final Exam Solutions

These are answers for questions that required composed solutions. Other questions can be checked by running the provided code in the problem text.

## Question 8
Create a Python function and name it next_word. The function should accept two positional arguments word and sentence. The function returns the word that comes directly after what is specified in the word argument. The returned value should be in the UPPER CASE.

In [8]:
# Solution 1
def next_word(word, sentence):
    index = sentence.find(word)
    index_space1 = sentence.find(' ', index)
    index_space2 = sentence.find(' ', index_space1 + 1)
    out = sentence[index_space1: index_space2]
    return out.upper()

# Solution 2
def next_word(word, sentence):
    words_list = sentence.split()
    for i, w in enumerate( words_list):
        if w.find(word) != -1:
            return words_list[i + 1].upper()

print( next_word(word = 'word', sentence = 'Several words create a sentence. ') )
print( next_word(sentence = 'The aroma of fresh coffee filled the air.', word = 'coffee') )
print( next_word('kitten', 'The playful kitten chased a fluttering butterfly.') )

CREATE
FILLED
CHASED


## Question 9

Write Python code that reads a dataset file and transforms it to a dictionary. The file follows the comma-separated values (CSV) format and has multiple lines. The first column values in the file should be used as the dictionary keys. The dictionary values are the numerical float numbers in the text file except the first column values.

The first line in the file is the column names (header), so it should be ignored when reading the file. Each remaining line represents a record in the dataset, the first value in each line (before the first comma) is the record identification value, and the remaining text is the record values after splitting. The figure below shows a visualization of the dataset structure.



In [ ]:
with open(path, 'r') as f:
    lines = f.readlines()
    d = {}
    for i in range(1,len(lines)):
        columns = lines[i].split(',')
        l = []
        for j in range(1, len(columns)):
            l.append(columns[j].strip())
        d[columns[0]] = l
    print(d)

## Question 11


In [9]:
l =[['A', 'B', 'C', 'D', 'E',],
    ['F', 'G', 'H', 'I', 'J',],
    ['K', 'L', 'M', 'N', 'O',],
    ['P', 'Q', 'R', 'S', 'T',],
    ['U', 'V', 'W', 'X', 'Y',],
    ['Z', 'AA', 'AB', 'AC', 'AD',],]

import numpy as np

arr = np.array(l)
print(arr[0:1,:])
print(arr[:,0:1])
print(arr[:,-2:-1])

[['A' 'B' 'C' 'D' 'E']]
[['A']
 ['F']
 ['K']
 ['P']
 ['U']
 ['Z']]
[['D']
 ['I']
 ['N']
 ['S']
 ['X']
 ['AC']]


## Question 12

A - arr[2:5,1:4]

B - A, K

## Question 13

Use Numpy to transform all the even numbers in the above array arr to zero. Your solution should be implemented in one line.



In [10]:
l2 = [
    [60,99,12,88,60],
    [43,51,47,58,80],
    [26,42,36,38,44],
    [97,53,92,97,97],
    [43,43,12,12,13],
    [33,23,21,82,90],
]

import numpy as np

arr = np.array(l2)

arr[(arr % 2 == 0)]=0	

print( arr )

[[ 0 99  0  0  0]
 [43 51 47  0  0]
 [ 0  0  0  0  0]
 [97 53  0 97 97]
 [43 43  0  0 13]
 [33 23 21  0  0]]


## Questio 14

The following function header suffers from several SyntaxErrors. Make the necessary corrections to this function header to make it work without adding additional lines.

```
def first_function(x.is_valid, noon_amount=0):
```

## Question 15

`arr[1: ,1:3]`


## Question 19

Given data about three cities in the dictionary below. Write code to print the information that includes the city name, population, and average household size, in a format that is identical to the provided output screenshot.

In [11]:
cities = {}
cities['El Paso'] = (678415, 2.92)
cities['Pittsburgh'] = (300431, 2.04)
cities['Fontana'] = (210761, 3.84)

print(f'{"City":>15} {"Population":>15} {"Avg. Household Size":>15}')
print(''.join(['-' for i in range(50)]))

for _, v in enumerate(cities):
    print(f'{v:>15} {cities[v][0]:>15,} {cities[v][1]:>15.1f}')
    print(''.join(['-' for i in range(50)]))

           City      Population Avg. Household Size
--------------------------------------------------
        El Paso         678,415             2.9
--------------------------------------------------
     Pittsburgh         300,431             2.0
--------------------------------------------------
        Fontana         210,761             3.8
--------------------------------------------------
